seed_everything: 7
trainer:
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_loss
        mode: min
        filename: '{epoch}-{step}-{val_loss:.2f}'
  # gpus: 1
  gpus: 1
  accelerator: gpu
  check_val_every_n_epoch: 2
  max_epochs: 310
  deterministic: true
  resume_from_checkpoint: null
model:
  d_model: 256
  # encoder
  growth_rate: 24
  num_layers: 16
  # decoder
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.3
  dc: 32
  cross_coverage: false
  self_coverage: false
  # beam search
  beam_size: 1
  max_len: 200
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  # training
  learning_rate: 0.08
  patience: 6
data:
  zipfile_path: data.zip
  test_year: 'all'
  train_batch_size: 32
  eval_batch_size: 16
  num_workers: 5
  scale_aug: true
  mask_ratio: 0.4
logger:
  project: 'CROHME MASK STAGE'
  name: '40 MASK'